image: "juliacomputing/juliapro:v1.4.2-1"

variables:
  JULIA_PKG_SERVER: pumas.juliateam.io
  PRIVATE_REGISTRY_NAME: PumasRegistry
  PRIVATE_REGISTRY_UUID: 2207cf11-c0bb-4826-96c6-61cddfb0e7e8
  REMOVE_JULIAPRO: "true"
  # GitLab requires that the cache path is insde the project
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"


cache:
  paths:
    - .julia/
    - docs/build

stages:
  - build:Pumas
  - build:PumasPlots
  - build:PumasPostProcessing
  - test
  - deploy:docs
  - deploy:pages

build_Pumas:
  stage: build:Pumas
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true)'
    - julia --color=yes --project=. -e 'using Pumas'
  only:
  - master
  - tags
  - external
  - pushes

build_PumasPlots:
  stage: build:PumasPlots
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
    - julia --color=yes --project=. -e 'using PumasPlots'
  only:
  - master
  - tags
  - external
  - pushes

build_PumasPostProcessing:
  stage: build:PumasPostProcessing
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
    - julia --color=yes --project=. -e 'using PumasPostProcessing'
  only:
  - master
  - tags
  - external
  - pushes

test:
  stage: test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - while sleep 30; do echo 'heart beat!' ; done &
    - julia --color=yes --project=. -e 'using Pkg; Pkg.test(coverage=true)'
  only:
  - master
  - tags
  - external
  - pushes

documentation:
  stage: deploy:docs
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'
    - julia --color=yes --project=docs/ docs/make.jl
  only:
  - master
  - tags
  - external
  - pushes

pages:
  stage: deploy:pages
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
